name: CI/CD

on: push

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vagtavadyan/ahoy:latest  # Please change the username here
  update_server:
    name: Updating prod environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker image pull vagtavadyan/ahoy
            docker container stop ahoy
            docker container prune -f
            docker run -d --name ahoy --restart unless-stopped -p 80:80 -p 443:443 vagtavadyan/ahoy
            docker image prune -f